image: node:latest

stages:
    - deploy

deploy:
    stage: deploy
    tags:
        - uig
    script:
        - echo "https://git.getprintbox.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
        - npm publish
